# Generated by Django 5.2.3 on 2025-07-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_payment_intent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
    ]
